[package]
name = "hyparview"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde"]
